#!/bin/bash
################################################################################
#                                  deploy                                      #
################################################################################
#                                                                              #
#  DESCRIPTION:  Quick script to consistently and reliably upload releases     #
#                to our website.                                               #
#                                                                              #
#  AUTHOR:       Mark Zieg <mzieg@wasatchphotonics.com>                        #
#                                                                              #
################################################################################

# @todo add WasatchVCPPNet installers
function renameAndPost()
{
    for PROJ in Setup32 Setup64
    do
        for TARGET in Debug Release
        do
            LOCAL_PATH="WasatchVCPPLib/$PROJ/$TARGET/WasatchVCPP-$PROJ-$VERSION.msi"
            REMOTE_FILE="WasatchVCPP-$VERSION-$PROJ-$TARGET.msi"
            if [ -f $LOCAL_PATH ]
            then
                scp $LOCAL_PATH $USERNAME@$REMOTE_HOST:$REMOTE_PATH/$REMOTE_FILE
            else
                echo "not found: $LOCAL_PATH"
            fi
        done
    done
}

REMOTE_HOST="wasatchphotonics.com"
REMOTE_PATH="www/binaries/drivers/Wasatch.VCPP"

read -p "Username: " USERNAME
read -p "Version:  " VERSION 

# verify version number in library
DRIVER_H=WasatchVCPPLib/WasatchVCPPLib/Driver.h
if egrep -q "libraryVersion = \"$VERSION\"" $DRIVER_H
then
    echo "Correct version in $DRIVER_H"
else
    echo "Can't find $VERSION in $DRIVER_H"
    exit 1
fi

# verify version number is tagged
if git tag | egrep -q $VERSION
then
    echo "Git tag found"
else
    echo "Git tag not found: $VERSION"
    exit 1
fi

# verify C headers match C# 
DIFF=`make check_headers`
echo "$DIFF"
if [ "$DIFF" != "" ]
then
    echo "Error: C and C# header mismatch"
    exit 1
fi

# render documentation 
echo "rendering docs"
export VERSION
make doc

# upload documentation
echo "uploading docs"
rsync --archive doxygen/html/ ${USERNAME}@wasatchphotonics.com:www/api/Wasatch.VCPP/

echo
echo "View via:"
echo
echo "    https://www.wasatchphotonics.com/api/Wasatch.VCPP/"
echo

renameAndPost
