#!/bin/bash
################################################################################
#                                  deploy                                      #
################################################################################
#                                                                              #
#  DESCRIPTION:  Quick script to consistently and reliably upload releases     #
#                to our website.                                               #
#                                                                              #
#  AUTHOR:       Mark Zieg <mzieg@wasatchphotonics.com>                        #
#                                                                              #
################################################################################

read -p "Username: " USERNAME
read -p "Version:  " VERSION 

# verify version number in library
DRIVER_H=WasatchVCPPLib/WasatchVCPPLib/Driver.h
if egrep -q "libraryVersion = \"$VERSION\"" $DRIVER_H
then
    echo "Correct version in $DRIVER_H"
else
    echo "Can't find $VERSION in $DRIVER_H"
    exit 1
fi

# verify version number is tagged
if git tag | egrep -q $VERSION
then
    echo "Git tag found"
else
    echo "Git tag not found: $VERSION"
    exit 1
fi

# render documentation 
export VERSION
make doc

# upload documentation
rsync --archive doxygen/html/ ${USERNAME}@wasatchphotonics.com:www/api/Wasatch.VCPP/

echo
echo "View via:"
echo
echo "    http://www.wasatchphotonics.com/api/Wasatch.VCPP/"
